In [1]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','NVIDIA','MSFT','FB','FB'],
       'Person':['Markie','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [2]:
df = pd.DataFrame(data)

In [3]:
df

  Company   Person  Sales
0    GOOG   Markie    200
1    GOOG  Charlie    120
2  NVIDIA      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [4]:
df.groupby('Company')

In [5]:
by_comp = df.groupby("Company")

In [6]:
by_comp.mean()

TypeError: dtype 'str' does not support operation 'mean'

In [7]:
df.groupby('Company').mean()

TypeError: dtype 'str' does not support operation 'mean'

In [9]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT     Vanessa    124
NVIDIA       Amy    340

In [10]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG      Markie    200
MSFT     Vanessa    124
NVIDIA       Amy    340

In [11]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          1      1
NVIDIA        1      1

In [12]:
by_comp.describe()

        Sales
        count   mean        std    min     25%    50%     75%    max
Company
FB        2.0  296.5  75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0  56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      1.0  124.0        NaN  124.0  124.00  124.0  124.00  124.0
NVIDIA    1.0  340.0        NaN  340.0  340.00  340.0  340.00  340.0

In [13]:
by_comp.describe().transpose()

Company              FB        GOOG   MSFT  NVIDIA
Sales count    2.000000    2.000000    1.0     1.0
      mean   296.500000  160.000000  124.0   340.0
      std     75.660426   56.568542    NaN     NaN
      min    243.000000  120.000000  124.0   340.0
      25%    269.750000  140.000000  124.0   340.0
      50%    296.500000  160.000000  124.0   340.0
      75%    323.250000  180.000000  124.0   340.0
      max    350.000000  200.000000  124.0   340.0

In [14]:
by_comp.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64